cc_test(
    name = "TupleTest",
    srcs = [
        "TupleTest.cpp",
        "Utility.hpp",
    ],
    deps = [
        "//src:SuperFastDB",
        "@com_google_googletest//:gtest",
    ],
)

cc_test(
    name = "TupleDescTest",
    srcs = [
        "TupleDescTest.cpp",
        "Utility.hpp",
    ],
    deps = [
        "//src:SuperFastDB",
        "@com_google_googletest//:gtest",
    ],
)
