cc_library(
    name = "utils",
    hdrs = [
        "status_builder.hpp",
        "status_macros.hpp",
    ],
    visibility = ["//visibility:public"],
    deps = [
        "@com_google_absl//absl/status",
        "@com_google_absl//absl/status:statusor",
        "@com_google_absl//absl/strings",
    ],
)
